[package]
name = "conv_image"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 3

[dependencies]
nannou_egui = "0.5.0"
nannou = "0.18.1"
rayon = "1.5.3"
